server:
  port: 8080

spring:
  application:
    name: PayrollManagementSystem

  datasource:
    url: jdbc:mysql://localhost:3306/payroll_management_system
    username: root
    password: sanjith
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  jackson:
    serialization:
      indent-output: true   # pretty print JSON

jwt:
  secret: X7kP9mL2qR5tY8uJ3vW6xZ0cN4bH1oE8iF2dG5jA9pL6kM3nQ8rT4wY7uI1vX2zC
  expirationMs: 86400000   # keep only ONE name (match with @Value in code)

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha
    display-request-duration: true
    filter: true

logging:
  level:
     org.springframework.web: INFO
     org.springdoc: INFO
     org.springframework.boot.autoconfigure.web.servlet.error: INFO
